apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        yurunbo/jx_0615: true
        yurunbo/jx_projec_demo_0614: true
        yurunbo/jx3_demo: true
        yurunbo/test-toBeDelete: true
        yurunbo/test-webhook: true
        yurunbo/webhook-demo-06015-1: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        yurunbo/jx_0615: merge
        yurunbo/jx_projec_demo_0614: merge
        yurunbo/jx3_demo: merge
        yurunbo/test-toBeDelete: merge
        yurunbo/test-webhook: merge
        yurunbo/webhook-demo-06015-1: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - yurunbo/jx3_demo
        - yurunbo/jx_0615
        - yurunbo/jx_projec_demo_0614
        - yurunbo/test-toBeDelete
        - yurunbo/test-webhook
        - yurunbo/webhook-demo-06015-1
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - yurunbo/jx3_demo
        - yurunbo/jx_0615
        - yurunbo/jx_projec_demo_0614
        - yurunbo/test-toBeDelete
        - yurunbo/test-webhook
        - yurunbo/webhook-demo-06015-1
      target_url: http://lighthouse-jx.41028y55e1.wicp.vip/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
