apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: yurunbo
    provider: github
    repository: test-webhook
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: yurunbo-test-webhook
  namespace: jx
spec:
  httpCloneURL: https://github.com/yurunbo/test-webhook.git
  org: yurunbo
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: test-webhook
  scheduler:
    kind: ""
    name: in-repo
  url: https://github.com/yurunbo/test-webhook
